POST http://localhost:3333/manga_livro
Content-Type: application/json

{
    "nome": "Tokyo Ghoul",
    "originador": "Sui Ishida",
    "capitulos": "150"
}

###

GET http://localhost:3333/manga_livro

###

GET http://localhost:3333/manga_livro?search=IFMS

###

PUT http://localhost:3333/mangas_livro/f43a9a30-83e3-4206-b193-0189e49b5009
Content-Type: application/json

{
    "nome": "Omniscient Reader Viewpoint",
    "originador": "Sing Shong",
    "capitulos": "178"
}

###

DELETE http://localhost:3333/mangas_livro/